services:
  fractal:
    build: 
      context: .
      dockerfile: Dockerfile
    entrypoint: yarn dev -- --host
    env_file:
      - .env
    ports:
      - 5173:5173
    volumes:
      - type: bind
        source: .
        target: /app