name: Deploy test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  deploy-test:
    runs-on: self-hosted
    steps:
    - name: Pull latest changes
      uses: actions/checkout@v4
    - name: Install dependencies
      run: cd /home/jwysocki/fractal-frontend && yarn install
