name: Deploy test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  deploy-test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Pull latest changes
      run: yarn install
