name: Deploy test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  deploy-test:
    runs-on: self-hosted
    steps:
    - name: Pull latest changes
      run:
        | 
        cd ${{ vars.FRONTEND_PATH }}
        git reset --hard HEAD
        git pull origin master
